"""Fix engine: source-range replacement with conflict detection.

Fixes are never generated by re-unparsing the AST (design doc §17); they are
character-range rewrites on the original source so comments and formatting
are preserved. Overlapping fixes are skipped and left as MANUAL.
"""

from __future__ import annotations

import difflib
import shutil
from pathlib import Path
from typing import List, Tuple

from .models import Diagnostic, Fix, FixMode


def collect_fixes(diagnostics: List[Diagnostic],
                  risky: bool = False) -> Tuple[List[Fix], int]:
    modes = {FixMode.AUTO_SAFE}
    if risky:
        modes.add(FixMode.AUTO_WARNING)
    fixes = [d.fix for d in diagnostics
             if d.fix is not None and d.fix_mode in modes]
    fixes.sort(key=lambda f: f.start)
    accepted: List[Fix] = []
    skipped = 0
    last_end = -1
    for f in fixes:
        if f.start < last_end:      # overlap conflict -> do not auto-fix
            skipped += 1
            continue
        accepted.append(f)
        last_end = f.end
    return accepted, skipped


def apply_fixes(path: Path, diagnostics: List[Diagnostic], risky: bool = False,
                dry_run: bool = False, backup: bool = False
                ) -> Tuple[int, int, str]:
    """Apply auto-safe fixes to a file.

    Returns (applied_count, skipped_conflicts, unified_diff_or_empty).
    """
    accepted, skipped = collect_fixes(diagnostics, risky=risky)
    original = path.read_text(encoding="utf-8")
    new_text = original
    for fix in reversed(accepted):
        new_text = new_text[:fix.start] + fix.new_text + new_text[fix.end:]

    diff = ""
    if new_text != original:
        diff = "".join(difflib.unified_diff(
            original.splitlines(keepends=True),
            new_text.splitlines(keepends=True),
            fromfile=str(path),
            tofile=str(path) + " (fixed)",
        ))

    if not dry_run and accepted and new_text != original:
        if backup:
            shutil.copy2(path, Path(str(path) + ".bak"))
        path.write_text(new_text, encoding="utf-8")
    return len(accepted), skipped, diff
