pull_request_rules:
  - name: Auto merge
    conditions:
      - "#changes-requested-reviews-by=0"
      - label=st:test-and-merge
      - status-success=Jenkins
      - status-success=continuous-integration/travis-ci/pr
      - status-success=pfn-public-ci/cupy.py3.amd
    actions:
      merge:
        method: merge
        strict: false  # strict mode and manually-triggered CIs do not get along
