# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2
submodules:
  include: all
  recursive: true
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
formats: all
sphinx:
  configuration: docs/source/conf.py
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
