# TODO: Migrate to pyproject.toml once ready

# Use the lowest supported version
target-version = "py39"
# Default value of autopep8
line-length = 80
exclude = ["docs/source/*", "third_party/*"]

[lint]
extend-select = [
  "I",      # isort
  "Q",      # flake8-quotes
  "TID252", # relative-imports
]
ignore = [
  "E402", # module-import-not-at-top-of-file
  "E721", # type-comparison
  "E74",  # ambiguous-XXX-name
]

[lint.per-file-ignores]
"__init__.py" = [
  "F401", # unused-import
]
"cupy/array_api/**/*.py" = [
  "F401", # unused-import
]
"tests/cupy_tests/array_api_tests/**/*.py" = [
  "F401", # unused-import
]
"cupyx/scipy/special/_gammainc.py" = [
  "E501", # line-too-long (numerical constants)
]

# Added for future use
[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
