cpdef enum cupy_cub_op:
    CUPY_CUB_SUM = 0
    CUPY_CUB_MIN = 1
    CUPY_CUB_MAX = 2
    CUPY_CUB_ARGMIN = 3
    CUPY_CUB_ARGMAX = 4
    CUPY_CUB_CUMSUM = 5
    CUPY_CUB_CUMPROD = 6
    CUPY_CUB_PROD = 7
