from cupy.cuda.stream import Stream

class Graph:
    def launch(self, stream: Stream | None = ...) -> None: ...
    def upload(self, stream: Stream | None = ...) -> None: ...
    def debug_dot_str(self, flags: int = ...) -> str: ...
