###
### Linux (CUDA) CI Projects
###

# CUDA 11.2 | Linux
configs {
  key: "cupy.linux.cuda112"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda112"
  }
}

# CUDA 11.2 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda112.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda112.multi"
  }
}

# CUDA 11.3 | Linux
configs {
  key: "cupy.linux.cuda113"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda113"
  }
}

# CUDA 11.3 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda113.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda113.multi"
  }
}

# CUDA 11.4 | Linux
configs {
  key: "cupy.linux.cuda114"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda114"
  }
}

# CUDA 11.4 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda114.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda114.multi"
  }
}

# CUDA 11.5 | Linux
configs {
  key: "cupy.linux.cuda115"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda115"
  }
}

# CUDA 11.5 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda115.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda115.multi"
  }
}

# CUDA 11.6 | Linux
configs {
  key: "cupy.linux.cuda116"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda116"
  }
}

# CUDA 11.6 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda116.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda116.multi"
  }
}

# CUDA 11.7 | Linux
configs {
  key: "cupy.linux.cuda117"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda117"
  }
}

# CUDA 11.7 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda117.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda117.multi"
  }
}

# CUDA 11.8 | Linux
configs {
  key: "cupy.linux.cuda118"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda118"
  }
}

# CUDA 11.8 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda118.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda118.multi"
  }
}

# CUDA 12.0 | Linux
configs {
  key: "cupy.linux.cuda120"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda120"
  }
}

# CUDA 12.0 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda120.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda120.multi"
  }
}

# CUDA 12.1 | Linux
configs {
  key: "cupy.linux.cuda121"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda121"
  }
}

# CUDA 12.1 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda121.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda121.multi"
  }
}

# CUDA 12.2 | Linux
configs {
  key: "cupy.linux.cuda122"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda122"
  }
}

# CUDA 12.2 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda122.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda122.multi"
  }
}

# CUDA 12.3 | Linux
configs {
  key: "cupy.linux.cuda123"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda123"
  }
}

# CUDA 12.3 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda123.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda123.multi"
  }
}

# CUDA 12.4 | Linux
configs {
  key: "cupy.linux.cuda124"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda124"
  }
}

# CUDA 12.4 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda124.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda124.multi"
  }
}

# CUDA 12.5 | Linux
configs {
  key: "cupy.linux.cuda125"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda125"
  }
}
# CUDA 12.5 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda125.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda125.multi"
  }
}

# CUDA 12.6 | Linux
configs {
  key: "cupy.linux.cuda126"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda126"
  }
}
# CUDA 12.6 (Multi-GPU) | Linux
configs {
  key: "cupy.linux.cuda126.multi"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda126.multi"
  }
}

# CUDA 11.x + CUDA Python
configs {
  key: "cupy.linux.cuda11x-cuda-python"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda11x-cuda-python"
  }
}

# CUDA + RAPIDS
configs {
  key: "cupy.linux.cuda-rapids"
  value {
    requirement {
      cpu: 12
      memory: 78
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 3600
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda-rapids"
  }
}

# CUDA + Example
configs {
  key: "cupy.linux.cuda-example"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 3600
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda-example"
  }
}

# CUDA + Slow
configs {
  key: "cupy.linux.cuda-slow"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 3600
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh cuda-slow"
  }
}

# CUDA + Slow (for stable branch)
configs {
  key: "cupy.linux.cuda-slow-stable"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 3600
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci-stable.sh cuda-slow"
  }
}

# CUDA + HEAD
configs {
  key: "cupy.linux.cuda-head"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda-head"
  }
}

# CUDA + HEAD (for stable branch)
configs {
  key: "cupy.linux.cuda-head-stable"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci-stable.sh cuda-head"
  }
}

# CUDA Build & Import without CUDA
configs {
  key: "cupy.linux.cuda-build"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 20
    }
    time_limit: {
      seconds: 3600
    }
    environment_variables { key: "GPU" value: "0" }
    command: ".pfnci/linux/main-flexci.sh cuda-build"
  }
}

# BENCHMARK
configs {
  key: "cupy.linux.benchmark.head"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh benchmark"
  }
}

configs {
  key: "cupy.linux.benchmark.pr"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 43200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh benchmark"
  }
}

# Array API
configs {
  key: "cupy.linux.array-api"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 7200
    }
    environment_variables { key: "GPU" value: "1" }
    command: ".pfnci/linux/main-flexci.sh array-api"
  }
}

###
### Windows (CUDA) CI Projects
###

configs {
  key: "cupy.win.cuda112"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 11.2 3.9 test"
  }
}

configs {
  key: "cupy.win.cuda113"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 11.3 3.9 test"
  }
}

configs {
  key: "cupy.win.cuda114"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 11.4 3.9 test"
  }
}

configs {
  key: "cupy.win.cuda115"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 11.5 3.10 test"
  }
}

configs {
  key: "cupy.win.cuda116"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 11.6 3.10 test"
  }
}

configs {
  key: "cupy.win.cuda117"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 11.7 3.10 test"
  }
}

configs {
  key: "cupy.win.cuda118"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 11.8 3.10 test"
  }
}

configs {
  key: "cupy.win.cuda120"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 12.0 3.10 test"
  }
}

configs {
  key: "cupy.win.cuda121"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 12.1 3.11 test"
  }
}

configs {
  key: "cupy.win.cuda122"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 12.2 3.12 test"
  }
}

configs {
  key: "cupy.win.cuda123"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 12.3 3.12 test"
  }
}

configs {
  key: "cupy.win.cuda124"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 12.4 3.12 test"
  }
}

configs {
  key: "cupy.win.cuda125"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 12.5 3.12 test"
  }
}

configs {
  key: "cupy.win.cuda126"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 72000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci\\windows\\run.bat 12.6 3.12 test"
  }
}
