###
### Windows (CUDA) CI Projects
###

configs {
  key: "cupy.win.cuda102"
  value {
    requirement {
      cpu: 8
      memory: 24
      disk: 10
      gpu: 2
      image: "windows"
    }
    time_limit {
      seconds: 36000
    }
    checkout_strategy {
      include_dot_git: true
    }
    environment_variables { key: "GPU" value: "2" }
    environment_variables { key: "CUPY_CI_CACHE_KERNEL" value: "1" }
    command: ".pfnci\\windows\\run.bat 10.2 3.7 test"
  }
}


###
### Linux (CUDA) CI Projects
###

# Project to build Docker images
configs {
  key: "cupy.prep-linux"
  value {
    requirement {
      cpu: 12
      memory: 64
      disk: 10
      image: "docker"
    }
    time_limit: {
      seconds: 3600
    }
    command: ".pfnci/linux/main-flexci-prep.sh"
  }
}

# CUDA 10.2 | Linux
configs {
  key: "cupy.linux.cuda102"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    environment_variables { key: "TAGS" value: "mini" }
    command: ".pfnci/linux/main-flexci.sh cuda102"
  }
}

# CUDA 11.0 | Linux
configs {
  key: "cupy.linux.cuda110"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda110"
  }
}

# CUDA 11.1 | Linux
configs {
  key: "cupy.linux.cuda111"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda111"
  }
}

# CUDA 11.2 | Linux
configs {
  key: "cupy.linux.cuda112"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda112"
  }
}

# CUDA 11.3 | Linux
configs {
  key: "cupy.linux.cuda113"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda113"
  }
}

# CUDA 11.4 | Linux
configs {
  key: "cupy.linux.cuda114"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    command: ".pfnci/linux/main-flexci.sh cuda114"
  }
}

# CUDA 11.5 | Linux
configs {
  key: "cupy.linux.cuda115"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    environment_variables { key: "TAGS" value: "mini" }
    command: ".pfnci/linux/main-flexci.sh cuda115"
  }
}

# CUDA 11.x + CUDA Python
configs {
  key: "cupy.linux.cuda11x-cuda-python"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    environment_variables { key: "TAGS" value: "cuda-python" }
    command: ".pfnci/linux/main-flexci.sh cuda11x-cuda-python"
  }
}

# CUDA + RAPIDS
configs {
  key: "cupy.linux.cuda-rapids"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 3600
    }
    environment_variables { key: "GPU" value: "1" }
    environment_variables { key: "TAGS" value: "rapids" }
    command: ".pfnci/linux/main-flexci.sh cuda-rapids"
  }
}

# CUDA + Doctest
configs {
  key: "cupy.linux.cuda-doctest"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 3600
    }
    environment_variables { key: "GPU" value: "2" }
    environment_variables { key: "TAGS" value: "doctest" }
    command: ".pfnci/linux/main-flexci.sh cuda-doctest"
  }
}

# CUDA + Example
configs {
  key: "cupy.linux.cuda-example"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 3600
    }
    environment_variables { key: "GPU" value: "2" }
    environment_variables { key: "TAGS" value: "mini,example" }
    command: ".pfnci/linux/main-flexci.sh cuda-example"
  }
}

# CUDA + HEAD
configs {
  key: "cupy.linux.cuda-head"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 2
    }
    time_limit: {
      seconds: 21600
    }
    environment_variables { key: "GPU" value: "2" }
    environment_variables { key: "TAGS" value: "head" }
    command: ".pfnci/linux/main-flexci.sh cuda-head"
  }
}

# Array API
configs {
  key: "cupy.linux.array-api"
  value {
    requirement {
      cpu: 8
      memory: 50
      disk: 10
      gpu: 1
    }
    time_limit: {
      seconds: 7200
    }
    environment_variables { key: "GPU" value: "1" }
    environment_variables { key: "TAGS" value: "array-api" }
    command: ".pfnci/linux/main-flexci.sh array-api"
  }
}
