# config.pbtxt is a config file for PFN's CI.
#
# Proto type: pfnci.protos.ConfigFile (http://go/pfnci-config-proto)
# NOTE: proto definition is still not open to the public.

configs {
  key: "cupy.py37.amd"
  value {
    requirement {
      cpu: 20
      memory: 30
    }
    time_limit: {
      seconds: 900
    }
    command: "bash .pfnci/script.sh py37.amd"
  }
}
