###############################################################################
# System
###############################################################################
# Target system to test on.
system:
  "linux":
  "windows":

###############################################################################
# OS
###############################################################################
# Name and version of the operating system to test on.
os:
  "ubuntu:20.04":
    system: "linux"
  "ubuntu:22.04":    # CUDA 11.7+
    system: "linux"
  "centos:7":
    system: "linux"
  "centos:8":
    system: "linux"
  "ws:2016":
    system: "windows"

###############################################################################
# CUDA & ROCm
###############################################################################
# The platform to test with.
# `cuda` and `rocm` are mutually exclusive; when one is set, the other must be null.
# `full_version` is the version used in base Docker images.
# `repository` is the Docker repository. (CUDA only)
# `packages` is the list of DEB/RPM packages to be installed. (ROCm only)
# When adding a new CUDA version, you may also need to add the version to the
# list of supported CUDA versions in the optional libraries.
cuda:
  null:
    full_version: null
    repository: null
  "11.2":
    full_version: "11.2.2"
    repository: "nvidia/cuda"
  "11.3":
    full_version: "11.3.1"
    repository: "nvidia/cuda"
  "11.4":
    full_version: "11.4.3"
    repository: "nvidia/cuda"
  "11.5":
    full_version: "11.5.2"
    repository: "nvidia/cuda"
  "11.6":
    full_version: "11.6.2"
    repository: "nvidia/cuda"
  "11.7":
    full_version: "11.7.1"
    repository: "nvidia/cuda"
  "11.8":
    full_version: "11.8.0"
    repository: "nvidia/cuda"
  "12.0":
    full_version: "12.0.1"
    repository: "nvidia/cuda"
  "12.1":
    full_version: "12.1.1"
    repository: "nvidia/cuda"
  "12.2":
    full_version: "12.2.0"
    repository: "nvidia/cuda"
  "12.3":
    full_version: "12.3.0"
    repository: "nvidia/cuda"
  "12.4":
    full_version: "12.4.0"
    repository: "nvidia/cuda"
  "12.5":
    full_version: "12.5.0"
    repository: "nvidia/cuda"
  "12.6":
    full_version: "12.6.0"
    repository: "nvidia/cuda"
rocm:
  null:
    full_version: null
    packages: []
  "4.3":
    full_version: "4.3.1"
    packages: ['rocm-dev', 'hipblas', 'hipfft', 'hipsparse', 'hipcub',
               'rocsparse', 'rocrand', 'rocthrust', 'rocsolver', 'rocfft',
               'rocprim', 'rccl']
  "5.0":
    full_version: "5.0"
    packages: ['rocm-dev', 'hipblas', 'hipfft', 'hipsparse', 'hipcub',
               'rocsparse', 'rocrand', 'rocthrust', 'rocsolver', 'rocfft',
               'rocprim', 'rccl']
  "5.3":
    full_version: "5.3"
    packages: ['rocm-dev', 'hipblas', 'hipfft', 'hipsparse', 'hipcub',
               'rocsparse', 'rocrand', 'rocthrust', 'rocsolver', 'rocfft',
               'rocprim', 'rccl']

###############################################################################
# CUDA Optional Libraries
###############################################################################
# The optional libraries to install: NCCL, cuTENSOR, cuSPARSELt and cuDNN.
# `spec` must be a version specifier accepted by apt and yum.
# `cuda` lists the supported CUDA version.
# `cuda.alias` (cuDNN/NCCL) is an alias name for package name suffix.
nccl:
  # https://docs.nvidia.com/deeplearning/nccl/archives/
  # https://developer.nvidia.com/nccl/nccl-download
  null:
    spec: null
  "2.16":
    spec: "2.16.*"
    cuda:
      # Note: DEB package for CUDA 11.x unavailable on Ubuntu 22.04
      # "11.0":
      "11.2":  # assumed
        alias: "11.8"
      "11.3":  # assumed
        alias: "11.8"
      "11.4":  # assumed
        alias: "11.8"
      "11.5":  # assumed
        alias: "11.8"
      "11.6":  # assumed
        alias: "11.8"
      "11.7":  # assumed
        alias: "11.8"
      "11.8":
      "12.0":
  "2.17":
    spec: "2.17.*"
    cuda:
      # "11.0":  -- DEB/RPM packages are unavailable
      "12.0":  # Note: DEB package unavailable on Ubuntu 22.04
      "12.1":
  "2.18":
    spec: "2.18.*"
    cuda:
      # "11.0":  -- DEB/RPM packages are unavailable
      "12.0":  # Note: DEB package unavailable on Ubuntu 22.04
      "12.2":
  "2.19":
    spec: "2.19.*"
    cuda:
      # "11.0":  -- DEB/RPM packages are unavailable
      "12.0":  # Note: DEB package unavailable on Ubuntu 22.04
      "12.2":
      "12.3":
  "2.20":
    spec: "2.20.*"
    cuda:
      # "11.0":  -- DEB/RPM packages are unavailable
      "12.0":  # Note: DEB package unavailable on Ubuntu 22.04
      "12.2":  # Note: DEB package unavailable on Ubuntu 22.04
      "12.3":
      "12.4":
  "2.21":
    spec: "2.21.*"
    cuda:
      "12.2":  # Note: DEB package unavailable on Ubuntu 22.04
      "12.4":
      "12.5":
  "2.22":
    spec: "2.22.*"
    cuda:
      "12.2":  # Note: DEB package unavailable on Ubuntu 20.04
      "12.4":
      "12.5":
      "12.6":
cutensor:
  # https://docs.nvidia.com/cuda/cutensor/
  # https://developer.nvidia.com/cutensor/downloads
  null:
    spec: null
  "2.0":
    spec: "2.0.*"
    cuda:
      # "10.2":  -- cuTENSOR distributed through binary package does not support CUDA 10.2
      # "11.0":
      "11.2":
      "11.3":
      "11.4":
      "11.5":
      "11.6":
      "11.7":
      "11.8":
      "12.0":
      "12.1":
      "12.2":
      "12.3":
      "12.4":
      "12.5":
      "12.6":
cusparselt:
  # https://docs.nvidia.com/cuda/cusparselt/
  # https://developer.nvidia.com/cusparselt/downloads
  null:
    spec: null
  "0.6.1":
    spec: "0.6.1.*"
    cuda:
      "12.0":
      "12.1":
      "12.2":
      "12.3":
      "12.4":
      "12.5":
      "12.6":
cudnn:
  # https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html
  # https://docs.nvidia.com/deeplearning/cudnn/archives/
  # https://developer.nvidia.com/rdp/cudnn-download
  null:
    spec: null
  "8.8":
    spec: "8.8.*"
    cuda:
      # "11.0":
      #   alias: "11.8"
      # "11.1":
      #   alias: "11.8"
      "11.2":
        alias: "11.8"
      "11.3":
        alias: "11.8"
      "11.4":
        alias: "11.8"
      "11.5":
        alias: "11.8"
      "11.6":
        alias: "11.8"
      "11.7":
        alias: "11.8"
      "11.8":
        alias: "11.8"
      "12.0":
        alias: "12.0"
      "12.1":  # TODO(kmaehashi): cuDNN 8.9 should be used
        alias: "12.0"
      "12.2":  # assumed
        alias: "12.0"
      "12.3":  # assumed
        alias: "12.0"
      "12.4":  # assumed
        alias: "12.0"
      "12.5": # assumed
        alias: "12.0"
      "12.6": # assumed
        alias: "12.0"

###############################################################################
# Python
###############################################################################
# Python version to test with.
# `spec` must be a version specifier accepted by pyenv.
# When adding a new Python version, you may also need to add the version to the
# list of supported Python versions in the Python libraries.
python:
  "3.10":
    spec: "3.10.0"
  "3.11":
    spec: "3.11.0"
  "3.12":
    spec: "3.12.0"
  "pre":
    spec: "3.13.0a1"  # note that dependency python libraies may not work

###############################################################################
# Python Libraries
###############################################################################
# Library versions to test with.
# `spec` must be a version specifier accepted by pip.
# When adding a new NumPy version, you may also need to add the version to the
# list of supported Python versions in SciPy.
numpy:
  "1.24":
    spec: "==1.24.*"
    python:
      - "3.10"
      - "3.11"
  "1.25":
    spec: "==1.25.*"
    python:
      - "3.10"
      - "3.11"
  "1.26":
    spec: "==1.26.*"
    python:
      - "3.10"
      - "3.11"
      - "3.12"
  "pre":
    spec: ">=0a0"  # latest, including pre-releases
scipy:
  # https://docs.scipy.org/doc/scipy/dev/toolchain.html#numpy
  null:
    # Note: Optuna depends on SciPy, so Optuna must also be set to null when
    # setting SciPy to null to run tests without SciPy.
    spec: null
  "1.10":
    spec: "==1.10.*"
    python:
      - "3.10"
      - "3.11"
    numpy:
      - "1.24"
  "1.11":
    spec: "==1.11.*"
    python:
      - "3.10"
      - "3.11"
      - "3.12"
    numpy:
      - "1.24"
      - "1.25"
      - "1.26"
  "1.12":
    spec: "==1.12.*"
    python:
      - "3.10"
      - "3.11"
      - "3.12"
    numpy:
      - "1.24"
      - "1.25"
      - "1.26"
  "pre":
    spec: ">=0a0"  # latest, including pre-releases
optuna:
  null:
    spec: null
  "3":
    spec: "==3.*"
  "pre":
    spec: ">=0a0"  # latest, including pre-releases
mpi4py:
  null:
    spec: null
  "3":
    spec: "==3.*"
cython:
  "0.29":
    spec: "==0.29.*"
  "pre":
    spec: ">=0a0"  # latest, including pre-releases
cuda-python:
  null:
    spec: null
  "11":
    spec: "==11.*"

###############################################################################
# Environment Variables
###############################################################################
env:CUPY_ACCELERATORS:
  null:                   # Default ("cub")
  "":                     # Disable all accelerators
  # "cub":                # Equivalent to null
  "cutensor":
  "cub,cutensor":
  "cutensor,cub":

###############################################################################
# Test Variant
###############################################################################
test:
  "unit":
  "unit-multi":
  "unit-slow":
  "example":
  "benchmark":
