###############################################################################
# System
###############################################################################
# Target system to test on.
system:
  "linux":
  "windows":

###############################################################################
# OS
###############################################################################
# Name and version of the operating system to test on.
os:
  "ubuntu:18.04":
    system: "linux"
  "ubuntu:20.04":
    system: "linux"
  "centos:7":
    system: "linux"
  "centos:8":
    system: "linux"
  "ws:2016":
    system: "windows"

###############################################################################
# CUDA & ROCm
###############################################################################
# The platform to test with.
# `cuda` and `rocm` are mutually exclusive; when one is set, the other must be null.
# `full_version` is the version used in base Docker images.
# When adding a new CUDA version, you may also need to add the version to the
# list of supported CUDA versions in the optional libraries.
cuda:
  null:
    full_version: null
  "10.2":
    full_version: "10.2"
  "11.0":
    full_version: "11.0.3"
  "11.1":
    full_version: "11.1.1"
  "11.2":
    full_version: "11.2.1"
  "11.3":
    full_version: "11.3.1"
  "11.4":
    full_version: "11.4.0"
  "11.5":
    full_version: "11.5.0"
  "11.6":
    full_version: "11.6.0"
  "11.7":
    full_version: "11.7.0"
rocm:
  null:
    full_version: null
    packages: []
  "4.3":
    full_version: "4.3.1"
    packages: ['rocm-dev', 'hipblas', 'hipfft', 'hipsparse', 'hipcub',
               'rocsparse', 'rocrand', 'rocthrust', 'rocsolver', 'rocfft',
               'rocprim', 'rccl']
  "5.0":
    full_version: "5.0"  # TODO(kmaehashi): bump to 5.0.2
    packages: ['rocm-dev', 'hipblas', 'hipfft', 'hipsparse', 'hipcub',
               'rocsparse', 'rocrand', 'rocthrust', 'rocsolver', 'rocfft',
               'rocprim', 'rccl']
  "5.1":
    full_version: "5.1.3"
    packages: ['rocm-dev', 'hipblas', 'hipfft', 'hipsparse', 'hipcub',
               'rocsparse', 'rocrand', 'rocthrust', 'rocsolver', 'rocfft',
               'rocprim', 'rccl']
  "5.2":
    full_version: "5.2"
    packages: ['rocm-dev', 'hipblas', 'hipfft', 'hipsparse', 'hipcub',
               'rocsparse', 'rocrand', 'rocthrust', 'rocsolver', 'rocfft',
               'rocprim', 'rccl']

###############################################################################
# CUDA Optional Libraries
###############################################################################
# The optional libraries to install: NCCL, cuTENSOR, cuSPARSELt and cuDNN.
# `spec` must be a version specifier accepted by apt and yum.
# `cuda` lists the supported CUDA version.
# `cuda.alias` (cuDNN only) is an alias name for package name suffix.
nccl:
  # https://docs.nvidia.com/deeplearning/nccl/archives/
  # https://developer.nvidia.com/nccl/nccl-download
  null:
    spec: null
  "2.8":
    spec: "2.8.*"
    cuda:
      # "10.1":
      "10.2":
      "11.0":
      "11.1":
      "11.2":
  "2.9":
    spec: "2.9.*"
    cuda:
      "10.2":
      "11.0":
      "11.3":
  "2.10":
    spec: "2.10.*"
    cuda:
      "10.2":
      "11.0":
      "11.4":
  "2.11":
    spec: "2.11.*"
    cuda:
      "10.2":
      "11.0":
      "11.4":
      "11.5":
      "11.6":
cutensor:
  # https://docs.nvidia.com/cuda/cutensor/
  # https://developer.nvidia.com/cutensor/downloads
  null:
    spec: null
  "1.4":
    spec: "1.4.*"
    cuda:
      # "10.2":  -- cuTENSOR distributed through binary package does not support CUDA 10.2
      "11.0":
      "11.1":
      "11.2":
      "11.3":
      "11.4":
      "11.5":
      "11.6":
  "1.5":
    spec: "1.5.*"
    cuda:
      # "10.2":  -- cuTENSOR distributed through binary package does not support CUDA 10.2
      "11.0":
      "11.1":
      "11.2":
      "11.3":
      "11.4":
      "11.5":
      "11.6":
      "11.7":
cusparselt:
  # https://docs.nvidia.com/cuda/cusparselt/
  # https://developer.nvidia.com/cusparselt/downloads
  null:
    spec: null
  "0.2.0":
    spec: "0.2.0.*"
    cuda:
      "11.2":
      "11.3":
      "11.4":
      "11.5":
      "11.6":
      "11.7":
cudnn:
  # https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html
  # https://docs.nvidia.com/deeplearning/cudnn/archives/
  # https://developer.nvidia.com/rdp/cudnn-download
  null:
    spec: null
  "7.6":
    spec: "7.6.*"
    cuda:
      # "10.0":
      # "10.1":
      "10.2":
  "8.0":
    spec: "8.0.*"
    cuda:
      # "10.1":  # note: RHEL 8 not supported
      "10.2":
      "11.0":
      "11.1":
  "8.1":
    spec: "8.1.*"
    cuda:
      "10.2":
      "11.0":
        alias: "11.2"
      "11.1":
        alias: "11.2"
      "11.2":
        alias: "11.2"
  "8.2":
    spec: "8.2.*"
    cuda:
      "10.2":
      "11.0":
        alias: "11.4"
      "11.1":
        alias: "11.4"
      "11.2":
        alias: "11.4"
      "11.3":
        alias: "11.4"
      "11.4":
        alias: "11.4"
      "11.5":
        alias: "11.4"
  "8.3":
    spec: "8.3.*"
    cuda:
      "10.2":
      "11.0":
        alias: "11.5"
      "11.1":
        alias: "11.5"
      "11.2":
        alias: "11.5"
      "11.3":
        alias: "11.5"
      "11.4":
        alias: "11.5"
      "11.5":
        alias: "11.5"
      "11.6":
        alias: "11.5"
  "8.4":
    spec: "8.4.*"
    cuda:
      "10.2":
      "11.0":
        alias: "11.6"
      "11.1":
        alias: "11.6"
      "11.2":
        alias: "11.6"
      "11.3":
        alias: "11.6"
      "11.4":
        alias: "11.6"
      "11.5":
        alias: "11.6"
      "11.6":
        alias: "11.6"
      "11.7":
        alias: "11.6"

###############################################################################
# Python
###############################################################################
# Python version to test with.
# `spec` must be a version specifier accepted by pyenv.
# When adding a new Python version, you may also need to add the version to the
# list of supported Python versions in the Python libraries.
python:
  "3.7":
    spec: "3.7.11"
  "3.8":
    spec: "3.8.11"
  "3.9":
    spec: "3.9.6"
  "3.10":
    spec: "3.10.0"
  "pre":
    spec: "3.11.0a1"  # note that dependency python libraies may not work

###############################################################################
# Python Libraries
###############################################################################
# Library versions to test with.
# `spec` must be a version specifier accepted by pip.
# When adding a new NumPy version, you may also need to add the version to the
# list of supported Python versions in SciPy.
numpy:
  "1.20":
    spec: "==1.20.*"
    python:
      - "3.7"
      - "3.8"
      - "3.9"
  "1.21":
    spec: "==1.21.*"
    python:
      - "3.7"
      - "3.8"
      - "3.9"
      - "3.10"
  "1.22":
    spec: "==1.22.*"
    python:
      - "3.8"
      - "3.9"
      - "3.10"
  "1.23":
    spec: "==1.23.*"
    python:
      - "3.8"
      - "3.9"
      - "3.10"
  "pre":
    spec: ">=0a0"  # latest, including pre-releases
scipy:
  # https://docs.scipy.org/doc/scipy/dev/toolchain.html#numpy
  null:
    # Note: Optuna depends on SciPy, so Optuna must also be set to null when
    # setting SciPy to null to run tests without SciPy.
    spec: null
  "1.6":
    spec: "==1.6.*"
    python:
      - "3.7"
      - "3.8"
      - "3.9"
    numpy:
      # - "1.16"
      # - "1.17"
      # - "1.18"
      # - "1.19"
      - "1.20"
  "1.7":
    spec: "==1.7.*"
    python:
      - "3.7"
      - "3.8"
      - "3.9"
      - "3.10"
    numpy:
      # - "1.16"
      # - "1.17"
      # - "1.18"
      # - "1.19"
      - "1.20"
      - "1.21"
      - "1.22"
  "1.8":
    spec: "==1.8.*"
    python:
      - "3.8"
      - "3.9"
      - "3.10"
    numpy:
      # - "1.17"
      # - "1.18"
      # - "1.19"
      - "1.20"
      - "1.21"
      - "1.22"
      - "1.23"
  "pre":
    spec: ">=0a0"  # latest, including pre-releases
optuna:
  null:
    spec: null
  "2":
    spec: "==2.*"
  "pre":
    spec: ">=0a0"  # latest, including pre-releases
cython:
  "0.29":
    spec: "==0.29.*"
  "pre":
    spec: ">=0a0"  # latest, including pre-releases
cuda-python:
  null:
    spec: null
  "11":
    spec: "==11.*"

###############################################################################
# Environment Variables
###############################################################################
env:CUPY_ACCELERATORS:
  null:
  "":
  "cub":
  "cutensor":
  "cub,cutensor":
  "cutensor,cub":

###############################################################################
# Test Variant
###############################################################################
test:
  "unit":
  "unit-multi":
  "unit-slow":
  "example":
  "benchmark":
