class Flags:
    def __init__(
        self, c_contiguous: bool, f_contiguous: bool, owndata: bool
    ) -> None: ...
    @property
    def c_contiguous(self) -> bool: ...
    @property
    def f_contiguous(self) -> bool: ...
    @property
    def owndata(self) -> bool: ...
    @property
    def fnc(self) -> bool: ...
    @property
    def forc(self) -> bool: ...
    def __getitem__(self, name: str) -> bool: ...
