/* Generated by Cython 0.29.37 */

#ifndef __PYX_HAVE__cupy___core__numpy_allocator
#define __PYX_HAVE__cupy___core__numpy_allocator

#include "Python.h"

#ifndef __PYX_HAVE_API__cupy___core__numpy_allocator

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C void *_calloc(size_t, size_t);
__PYX_EXTERN_C void *_malloc(size_t);
__PYX_EXTERN_C void *_realloc(void *, size_t);
__PYX_EXTERN_C void _free(void *);

#endif /* !__PYX_HAVE_API__cupy___core__numpy_allocator */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initnumpy_allocator(void);
#else
PyMODINIT_FUNC PyInit_numpy_allocator(void);
#endif

#endif /* !__PYX_HAVE__cupy___core__numpy_allocator */
