name: "Auto Notify"

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]

permissions:
  issues: write

jobs:
  auto-notify:
    if: |
        github.repository_owner == 'cupy' &&
        contains('|hip|array-api|', github.event.label.name)
    env:
      NOTIFY_TARGETS: '{"hip": "@gpinkert", "array-api": "@asmeurer @leofang"}'
      ISSUE_NUMBER: ${{ (github.event_name == 'issues' && github.event.issue.number) || github.event.pull_request.number }}
      ISSUE_BODY_TAG: "<!-- Added by Auto Notify Bot (${{ github.event.label.name }}) -->"
    runs-on: ubuntu-22.04

    steps:
      - name: Find comment
        uses: peter-evans/find-comment@a54c31d7fa095754bfef525c0c8e5e5674c4b4b1  # v2.4.0
        id: fc
        with:
            issue-number: ${{ env.ISSUE_NUMBER }}
            body-includes: ${{ env.ISSUE_BODY_TAG }}

      - name: Create comment
        uses: peter-evans/create-or-update-comment@67dcc547d311b736a8e6c5c236542148a47adc3d  # v2.1.1
        with:
            issue-number: ${{ env.ISSUE_NUMBER }}
            comment-id: ${{steps.fc.outputs.comment-id}}
            edit-mode: replace
            body: |
                ${{ env.ISSUE_BODY_TAG }}
                cc/ ${{ fromJSON(env.NOTIFY_TARGETS)[github.event.label.name] }}
