name: "Pre-review Tests"

on: [push, pull_request]

jobs:
  static-checks:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        # Checkout using commit hash to make "no-commit-to-branch" test pass.
        ref: ${{ github.sha }}
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: '3.12'

    - name: Setup cache
      uses: actions/cache@v4
      with:
        path: ~/.cache
        key:
          static-checks-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys:
          static-checks-

    - name: Setup pre-commit
      run: |
        pip install pre-commit

    - name: Check
      run: |
        pre-commit run -a --show-diff-on-failure

    - name: Type Check
      run: |
        # TODO: Test against various NumPy/SciPy versions.
        pip install 'numpy==2.3.*' 'scipy==1.16.*'
        pip install 'mypy==2.3.*' 'types-setuptools==57.4.14' 'pytest>=7.2'
        sed -i s/error::cupy.exceptions./error::numpy.exceptions./ pyproject.toml  # Because no cupy here. See cupy#8346
        pytest -v tests/typing_tests/test_typing.py

  build-rocm:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build & Test
      run: |
        # Note: "-complete" Docker image variants exceeds disk size on GitHub hosted runners.
        docker run --rm -v "${PWD}:/src" -w /src "rocm/dev-ubuntu-22.04:7.14.0-full" bash .github/workflows/scripts/pretest-rocm-test.sh
